name: Image build

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

env:
  IMAGE_NAME: ticket-mn-api
  JWT_ACCESS_TOKEN_SECRET: ${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
  JWT_ACCESS_TOKEN_EXPIRATION_MS: 10000
  JWT_REFRESH_TOKEN_SECRET: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
  JWT_REFRESH_TOKEN_EXPIRATION_MS: 36000
  NODE_ENV: dev
  REDIS_URL: ${{ secrets.REDIS_URL }}
  DB_URI: ${{ secrets.DB_URI }}
  GIN_MODE: release
jobs:

  push:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker compose build ticket-mn-api
      - name: Tag with Image
        run: docker tag ticket-mn-api:latest $IMAGE_NAME:$GITHUB_SHA
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push to registry
        run: |
          IMAGE_ID=ghcr.io/nodejs-typescript-classroom/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION